### ISSUE TITLE
How do I get a handler for the stored certificates

### ISSUE THREAD

**Issue by serafdev** [ThalesGroup/pycryptoki#17]
So I'm writing some script that needs to connect to an external server which requires me to present a client certificate for the SSL Handshake.

My private key is stored in the HSM, I was able to use the sample code to generate a key pair but I do not see a way to add a handler to pass to my code for the SSL handshake.

Here's how my code looks like:

```python
from pycryptoki.session_management import (
    c_initialize_ex,
    c_open_session_ex,
    login_ex,
    c_logout_ex,
    c_close_session_ex,
    c_finalize_ex,
)
from requests import Session
from zeep import Client
from zeep.transports import Transport

from app.settings import BASE_DIR

c_initialize_ex()
auth_session = c_open_session_ex(0)
login_ex(auth_session, 0, "some-pass")

session: Session = Session()
session.cert = (
    "/path/to/company1.com.pem",
    "rsa-private-156405640312",
)
session.verify = os.path.join(
    BASE_DIR, os.path.join("run", "company2.pem")
)
client: Client = Client(
    f"https://company2.com/api/v9/connector.cgi",
    transport=Transport(session=session),
)
client.settings(raw_response=True)

c_logout_ex(auth_session)
c_close_session_ex(auth_session)
c_finalize_ex()
```

The important line are these ones for now:

```python
session.cert = (
    "/path/to/company1.com.pem",
    "rsa-private-156405640312",
)
```

Which are used to present the client's public certificate to authenticate itself, and passing as the second element of the tupple the key for decryption so the session knows how to decrypt the information.

My problem is I don't know what to put there, I tried with the label of the key in the HSM but that doesn't work, I'm guessing that I need to create a X509 object with some type of handler?

I'm not sure how to solve this and how to point to the key, any help would be great!

Thank you in advance

**Comment by serafss2** [comment]
I tried what you said, I did the integration and tried the label as the "keyfile" and indeed it doesn't work, I will investigate on how I could bypass the file validator from the ssl library underneath.

Meanwhile I'm not binded to using Python, if you guys have a solution in another language (that has a compiler on linux) I will be more than glad in using it. Let me know if you have such implementation somewhere as an example!

Thank you so much @astraw38 for your time!

**Comment by mdhgarcia** [comment]
If I'm understanding correctly and what you need is to present a certificate signed by the private key in the HSM - because presumably the self-signed cert from the HSM is trusted by the server - I think I solved this particular problem (though if I don't understand correctly I've solved a different problem...). The (messy) solution looks something like the following:
1. Hand-build a TBS (to-be-signed) certificate using the pyasn1 library (this is the raw ASN.1 data that a CSR presents for signing). This involves creating a TBS header with (I believe) at least the CN, validity dates, and public key for signing.
3. Look up handles for the HSM's self-signed cert and private key by label
4. Export the HSM's self-signed cert (if you need to present the full chain)
5. Hash the TBS cert with the appropriate function
6. Sign the TBS cert hash with the HSM's private key
7. Append the signature to the TBS cert in the appropriate field to complete the full X.509 cert

If instead what you need (or maybe both) is to present a certificate to the server so it can encrypt some data for you to decrypt in the HSM, you can create a self-signed cert in the HSM using the `cmu` utility (I suppose you could hand-build that too and sign the HSM's own public key with its private key if you don't want to use command-line utils) and pass that to the sever.

Hope that helps! It cost me a lot of time and a hole in the wall from banging my head repeatedly...

PS: If someone at Thales would be so kind, implementing helper functions for generating a TBS cert from a public key and passing it into the HSM for signing would be much appreciated... I know cmu does this but the library doesn't AFAIK. I can also ask my employer whether they'd be willing to open-source this particular function!
