### ISSUE TITLE
How to Extract Public Key

### ISSUE THREAD

**Issue by a6r2u8n** [ThalesGroup/pycryptoki#26]
Is it possible to extract RSA public key ? 
like option 32 - OBJECT MANAGEMENT in ckdemo

**Comment by astraw38** [comment]
Yes, but you'd need to do the DER encoding manually. That option does the following things:

1. `C_GetAttributeValue()` to get `CKA_MODULUS` and `CKA_PUBLIC_EXPONENT` (can be done in pycryptoki va `c_get_attribute_value`)
2. DER Encodes those values & write them to file.

It's an ASN.1 encoding (and there's an asn1 library in python to help you convert):

```
SEQUENCE
   BIT_STRING (KeyLen)
   SEQUENCE
     INTEGER (modulus)
     INTEGER (public exponent)
```


Alternatively, since you can get the e/n values, you can use the [cryptography](https://cryptography.io/en/latest/hazmat/primitives/asymmetric/rsa/#numbers) library to create public numbers object directly, and then export them to whatever format you want (DER/PEM)
